0x0C. Web server: DevOps, SysAdmin

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,1 +1,28 @@
 #!/usr/bin/env bash
+# configures a brand new Ubuntu machine to the requirements:
+# Configure your Nginx server so that `/redirect_me` is redirecting to another page
+
+# Exit immediately if a command exits with a non-zero status
+# set -e
+
+# Update package index//list and install Nginx
+sudo apt-get update -y
+sudo apt-get install -y nginx
+
+# Start Nginx service
+sudo service nginx start
+
+# Allow OpenSSH and Nginx HTTP traffic through the firewall
+# sudo ufw allow 'OpenSSH'
+# sudo ufw allow 'Nginx HTTP'
+
+sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
+
+# Create a custom HTML file for redirection
+echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=https://github.com/OluTshegz></head><body></body></html>" | sudo tee /var/www/html/redirect_me.html
+
+# Configure Nginx for redirection
+sudo sed -i '/listen 80 default_server/a return 301 https://github.com/OluTshegz;' /etc/nginx/sites-available/default
+
+# Restart Nginx service
+sudo service nginx restart
